### ISSUE TITLE
Malformed command 'CALIBRATE_Z BED_POSITION=(0, 0)'

### ISSUE THREAD

**Issue by pyunramura** [Frix-x/klipper-voron-V2#27]
I'm getting the above error when the print_start macro calls the auto_z_calibration macro with the computed mesh_center.

Not sure what exactly the issue is, rather I'm not sure why the {mesh_center} variable is passing `(0, 0)` instead of `(0,0)` or `(174,174)` to the CALIBRATE_Z macro. I believe CALIBRATE_Z BED_POSITION=(0,0) syntax works correctly as I tried that when I ran it manually.

The entire bed_mesh.cfg was copied verbatim and include behavior is working as expected.

Here is a excerpt from my PRINT_START macro if it will help.

```
...
{% set FL_SIZE = params.SIZE|default("0_0_0_0")|string %}
COMPUTE_MESH_PARAMETERS SIZE={FL_SIZE}

SCRUB

{% set mesh_center = printer["gcode_macro _ADAPTIVE_MESH_VARIABLES"].mesh_center %}
CALIBRATE_Z BED_POSITION={mesh_center}

BED_MESH_CLEAR
Attach_Probe_Lock
ADAPTIVE_BED_MESH
Dock_Probe_Unlock
...
```

Here is the console output from the commands leading up to the error

```
RELATIVE_REFERENCE_INDEX=12 ALGORITHM=bicubic
Computed mesh parameters: MESH_MIN=120,120 MESH_MAX=229,229 MESH_CENTER=174,174 PROBE_COUNT=5,5 ...
!! Malformed command 'CALIBRATE_Z BED_POSITION=(0, 0)'
!! Malformed command 'CALIBRATE_Z BED_POSITION=(0, 0)'
```

I'd appreciate any insight.

**Comment by Frix-x** [comment]
Hey! Thank you for raising an issue here. You are not the first one to experience it, it's quite a common issue and I will definitely need to add some documentation about that! I will first try to explain it as I can here :)

In fact the problem is coming from the way Klipper is working. There is like a big table in the memory which contain all the variables and their associated values. When you start a macro (like your PRINT_START), Klipper is doing a copy of this table in a local space, internal to the macro. Then if you do something in the macro like changing a value or something, it will not be updated in this internal copy (like when you call my computer parameters macro that create and update a "mesh_center" variable). So in order to access it, you need to start a new macro that will have it's own new local copy (including the updated values). I don't know if it's clear how I explained it but now I will explain how to solve the issue.

So what's happens in your PRINT_START ? First you compute the parameters, this looks to work correctly when looking at the logs. Then the variable `printer["gcode_macro _ADAPTIVE_MESH_VARIABLES"].mesh_center` exist in the global memory but not in the local memory of the PRINT_START. This means that you cannot do this directly after it:
```
{% set mesh_center = printer["gcode_macro _ADAPTIVE_MESH_VARIABLES"].mesh_center %}
CALIBRATE_Z BED_POSITION={mesh_center}
```

So in order to correct it, you will either need to move that two lines in another dumb macro that will have it's own updated memory or you can also integrate this logic directly in the CALIBRATE_Z override as I've done. See here: [macros/probing/z_calibration.cfg](https://github.com/Frix-x/klipper-voron-V2/blob/main/macros/probing/z_calibration.cfg)
